### ISSUE TITLE
Pre-processed dataset not downloading

### ISSUE THREAD

**Issue by ask2901** [HKU-MedAI/GEM-3D#3]
I tried to download the dataset but after downloading 6gb it stopped saying download failed. Tried on multiple system but the same issue persisted. Is anyone else facing the same issue?

**Comment by Advocate99** [comment]
Hi, I think this is caused by network issues. Resuming several times can finish the downloading.
I just try downloading with a different environment and I can download normally. You can try using a different network.
If you still have trouble doing that. Please contact me via email and I can send you the zip file via other ways.

**Comment by ask2901** [comment]
Switching networks is kind of not feasible, kindly share your email. Thanks!!

**Comment by Jason-u** [comment]
could you please share your email again?I can not download the preprocessed dataset
